apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  postgres-user: <your-encoded-postgres-user>
  postgres-password: <your-encoded-postgres-password>
  postgres-url: <your-encoded-postgres-url>