apiVersion: apps/v1
kind: Deployment
metadata:
  name: infoplex-backend-deployment
  labels:
    app: infoplex-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infoplex-backend
  template:
    metadata:
      labels:
        app: infoplex-backend
    spec:
      containers:
      - name: infoplex-backend
        image: <backend-image>
        ports:
        - containerPort: 8080
        env: # environment variables for the container
        - name: JDBC_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: postgres-url
        - name: CORS_ALLOWED_ORIGINS
          value: http://localhost:4200
        - name: JDBC_DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: postgres-user
        - name: JDBC_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: postgres-password

---
apiVersion: v1
kind: Service
metadata:
  name: infoplex-backend-service
spec:
  type: NodePort
  selector:
    app: infoplex-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30200
